# Generated by Django 5.2.11 on 2026-03-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_auditlog_description_alter_sale_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.customer'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.supplier'),
        ),
    ]
