# Generated by Django 5.2.11 on 2026-03-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stocktransaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='main.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='main.sale'),
        ),
    ]
