# Generated by Django 5.2.11 on 2026-03-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_saleitem_product_id_alter_saleitem_sale_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
